// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTKB9NK3jrzWCVGkrCL2FEAKvsNALLsEI',
    appId: '1:248955049292:web:8dd001063343e47d87abe9',
    messagingSenderId: '248955049292',
    projectId: 'demoresturent',
    authDomain: 'demoresturent.firebaseapp.com',
    storageBucket: 'demoresturent.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9w7oz54jQbbgxJkUCbELXv-NxR5mtAso',
    appId: '1:248955049292:android:39e10c1e4753ff2387abe9',
    messagingSenderId: '248955049292',
    projectId: 'demoresturent',
    storageBucket: 'demoresturent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2YNbtLcQfs5DGIihNHCEbfkuZK0mmLdg',
    appId: '1:248955049292:ios:86007c281c49fb6687abe9',
    messagingSenderId: '248955049292',
    projectId: 'demoresturent',
    storageBucket: 'demoresturent.appspot.com',
    iosBundleId: 'com.example.firebaseexercise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2YNbtLcQfs5DGIihNHCEbfkuZK0mmLdg',
    appId: '1:248955049292:ios:e6959818c6d71e1787abe9',
    messagingSenderId: '248955049292',
    projectId: 'demoresturent',
    storageBucket: 'demoresturent.appspot.com',
    iosBundleId: 'com.example.firebaseexercise.RunnerTests',
  );
}
